# Generated by Django 5.2.1 on 2025-07-10 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MetodosNumericos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculoBiseccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecuacion', models.CharField(max_length=100)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('tolerancia', models.FloatField(default=0.0001)),
                ('resultado', models.TextField()),
            ],
        ),
    ]
